id: 1c2cb9fcf0a940b3966d2f9ed17e045d
initial_creation_type: ocr
source_metadata:
  volumes:
    723bd8b608f04cd3ab0df22fc03fcf5f:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: ''
      total_pages: 2043
      volume_number: 13
